---

- name: install tar on Fedora 24
  dnf:
    name: tar
    state: present
  when: ansible_distribution == "Fedora" and ansible_distribution_major_version == "24"

- name: Create directories for Webstorm
  file:
    path: "{{ item }}"
    state: directory
  with_items:
  - "{{ webstorm_download_directory }}"
  - "{{ webstorm_install_directory }}"
  - "{{ webstorm_desktop_file_location | dirname }}"


- name: Download Webstorm plugins
  get_url:
    url: "{{ webstorm_plugin_download_mirror }}{{ item }}"
    dest: "{{ webstorm_download_directory }}"
  register: webstorm_plugins
  with_items: "{{ webstorm_plugins }}"

- name: Install WebStorm
  unarchive:
    copy: no
    src: "{{ webstorm_download_url}}"
    dest: "{{ webstorm_install_directory }}"
    creates: "{{ webstorm_location }}/bin/webstorm.sh"

- name: Install WebStorm Plugins
  unarchive:
    src: "{{ item.dest }}"
    dest: "{{ webstorm_location }}/plugins"
  with_items: "{{ webstorm_plugins.results }}"

- name: Create Webstorm desktop entry
  template:
    src: webstorm.desktop.j2
    dest: "{{ webstorm_desktop_file_location }}"
